version: '3'

services:
  nginx-gypsart:
    image: nginx:latest
    container_name: gypsart-nginx
    hostname: gypsart.com
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NGINX_HOST=gypsart.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-gypsart.rule=Host(`gypsart.com`)
      - traefik.http.routers.nginx-gypsart.entrypoints=websecure
      - traefik.http.routers.nginx-gypsart.tls=true
      - traefik.http.routers.nginx-gypsart.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-gypsart.loadbalancer.server.port=80
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере