name: Send Telegram Notification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v2
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "GitHub Action: New push or pull request on master branch for gypsart.com"
